// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Msg string `json:"msg"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Msg string `json:"msg"`
}
